### ISSUE TITLE
Upgrade to wkhtmltopdf 0.12.5

### ISSUE THREAD

**Issue by barredterra** [frappe/bench#897]
Can we upgrade wkhtmltopdf from `0.12.3` to `0.12.5` in easy install?

* wkhtmltopdf has been locked down to `0.12.3` intentionally since `0.12.4` had problems.
* I can confirm `0.12.5` is working fine with Ubuntu 18.04 and CentOS 7.6 and produces better results.

Ubuntu 18.04 amd64:
```yaml
- name: Download wkhtmltox
  get_url:
    url: https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
    dest: /tmp/wkhtmltox.deb

- name: Install wkhtmltox
  apt:
    deb: /tmp/wkhtmltox.deb
```

CentOS 7.6 x86_64:
```yaml
- name: Download wkhtmltox
  get_url:
    url: https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox-0.12.5-1.centos7.x86_64.rpm
    dest: /tmp/wkhtmltox.rpm

- name: Install wkhtmltox
  yum:
    name: /tmp/wkhtmltox.rpm
    state: present
```
